### ISSUE TITLE
add log output for `project create` command

### ISSUE THREAD

**Issue by capsulecorplab** [Mach30/m30pm#39]
as to be able to debug errors encountered during `project create`

**Comment by j-simmons-phd** [comment]
We have also mentioned adding a verbose output mode. In the interest of keeping the architecture simple, I think we should pick one of these approaches instead of doing both (for now). 

I am leaning toward logging as the implementation to go with. My rationale is that logging would be easier to implement (given the recent work on the fs lib) and a more flexible use case (e.g. can collect multiple runs and compare them).

**Comment by j-simmons-phd** [comment]
Specifications for Logging feature. 

1. Add a setting field for managing logging to ProjectConfiguration, stored in package.json
2. Add a .logs/ directory for storing log files to createProject() and include it in .gitignore
3. I expect we will primarily be logging CommandHistories
4. We should record two copies of logs (raw data structures in form of yaml files and formatted views as md files)
5. Log filenames should formatted YYYYMMDD-HHMM-<operation-title>-log.<yaml|md> where time is in 24 hour time.

I would like to develop a common view log view description to keep implementation simpler.

**Comment by capsulecorplab** [comment]
example log output from projectCreate() [log.json](https://github.com/user-attachments/files/16789227/log.json)

**Comment by capsulecorplab** [comment]
> example log output from projectCreate() [log.json](https://github.com/user-attachments/files/16789227/log.json)
Generated using `yq -o=yaml log.json`

**Comment by capsulecorplab** [comment]
closed as per ad84e1fb
