### ISSUE TITLE
using ./ vs CWD

### ISSUE THREAD

**Issue by capsulecorplab** [Mach30/m30pm#8]
Consider using `./` vs `CWD` keyword for specifying current working directory

**Comment by j-simmons-phd** [comment]
Actually, I have been thinking about this option and I have a different idea.  The project path should be defined as the directory containing the project settings file. I actually feel a little silly not having thought of it that way sooner. 

This then leads to one other change in the tool. There needs to be a cli option to specify the path to the settings file instead of the project path. When not specified it looks in ./ for the settings file name and if it doesn't find it, errors out. When specified the tool uses the directory where the settings file is as the project path. 

Ultimately, this means we remove the project path from the settings.

**Comment by j-simmons-phd** [comment]
So, I kept pondering this thread and thought of something else...  M30ml uses data from the package.json in the model generation process to pick up details like project name, version, and author. 

What if we moved the tools settings into a custom subsection of the package.json file?  It appears to be perfectly valid for npm and would consolidate our config files (later Sliderule could leverage the same approach).

https://stackoverflow.com/questions/10065564/add-custom-metadata-or-config-to-package-json-is-it-valid

**Comment by capsulecorplab** [comment]
I think it could be both; the project path, by default, could be relative to where the package.json is located, but you could override the default path by specifying a new relative path in package.json

**Comment by j-simmons-phd** [comment]
Ah, good call, yes I think that is the way to go.

**Comment by j-simmons-phd** [comment]
OBE with mono-repo and CLI approach
